---

# Main tasks file for halyard role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::halyard'
    - 'role::halyard::init'
